version: "3"

services:

  maven-welcome-servlet:
    build: blackened/maven-servlet/
    container_name: "welcome_tomcat_maven"
    ports:
      - "8080:8080"
      - "8443:8443"

  glassfish-welcome:
    build: blackened/glassfish-easy
    container_name: "glassfish"
    ports:
      - "8091:8080"
      - "8454:8443"
      - "4859:4848"
